Force gnu++98 language standard for native extension
This is required when building with GCC 6.0 because of the following
compiler error:

internal/cld_generated_cjk_uni_prop_80.cc:7089:1: error: narrowing conversion of ‘-14’ from ‘int’ to ‘CLD2::uint8 {aka unsigned char}’ inside { } [-Wnarrowing]